from pyrannic.contracts.orm.model import ModelInterface
from pyrannic.contracts.support.serializable import SerializableInterface
from pyrannic.support import inflect, string

_SUFFIXES_TO_REMOVE = ["Model", "Entity", "Schema", "Table"]


class AbstractModel(ModelInterface, SerializableInterface):
    @classmethod
    def is_intermediate_table(cls) -> bool:
        return False

    @classmethod
    def tablename(cls) -> str:
        """
        Return the table name for the model.
        The table name is generated by removing common suffixes (like "Model", "Entity", "Schema", "Table")
        from the class name and converting it to snake_case and pluralizing it.
        """
        name = cls.__name__

        for suffix in _SUFFIXES_TO_REMOVE:
            if name.endswith(suffix):
                name = name.replace(suffix, "", 1)

        snake_case_name = string.to_snake_case(name)

        if cls.is_intermediate_table():
            # For intermediate tables, we want to pluralize the each part of the name and separate it again with underscores.
            # For example, if the class name is "UserRole", we want to return "users_roles".
            parts = snake_case_name.split("_")
            pluralized_parts = [inflect.pluralize(part) for part in parts]
            tablename = "_".join(pluralized_parts)
        else:
            tablename = inflect.pluralize(snake_case_name)

        return tablename
